### ISSUE TITLE
是否考虑将其打成 docker 镜像？

### ISSUE THREAD

**Issue by Peatechen** [ChaosNyaruko/ondict#20]
哦，我注意到这个似乎能满足的我需求，https://github.com/ninja33/mdx-server

**Comment by Peatechen** [comment]
我注意到它能作为一个服务运行，但是我希望能够使用 docker 将其部署在服务器上

**Comment by ChaosNyaruko** [comment]
抱歉现在才看到，其实我这个也支持，你可以通过这个作者

**Comment by ChaosNyaruko** [comment]
@ChaosNyaruko Docker support
